secrets:
  admin_credentials:
    file: secrets/admin_credentials.txt
  client_secret:
    file: secrets/client_secret.json
  master_key:
    file: secrets/master_key.txt

services:
  app:
    build: .
    container_name: ktor_app
    depends_on:
      - postgres-db
    secrets:
      - admin_credentials
      - client_secret
      - master_key
    environment:
      DATABASE_USER: ktor_user
      DATABASE_PASSWORD: ktor_password
      CREDS_FILE: /run/secrets/admin_credentials
      CLIENT_SECRET: /run/secrets/client_secret
      DATABASE_URL: jdbc:postgresql://postgres-ua.developer.artemmotuznyi.db:5432/ktor_db
      MAIL_TOKEN_MASTER_KEY: /run/secrets/master_key
      PORT: 8080
      # Production OAuth redirect URI (should be set to actual server domain)
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI:-http://localhost:8080/oauth2callback}
      # Allowed CORS host for production
      ALLOWED_HOST: ${ALLOWED_HOST:-localhost:8080}
      JWT_SECRET : ${JWT_SECRET:-your_jwt_secret_here}
    ports:
      - "8080:8080"
    # Remove debug port for production security

  postgres-db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ktor_db
      POSTGRES_USER: ktor_user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-ktor_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.1.0
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    depends_on:
      - postgres-db
    profiles:
      - dev  # Only include in development

volumes:
  postgres_data: