services:
  cashacs:
    image: ktor-docker-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KTOR_DEPLOYMENT_PORT=8080
    restart: unless-stopped